apiVersion: v1
kind: Namespace
metadata:
  name: alterseccomp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alterseccomp
  namespace: alterseccomp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alterseccomp-cluster-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create"]
- apiGroups: ["security.openshift.io"]
  # It is necessary to use the 'privileged' security context constraints to be
  # able mount host directories as volumes, use the host networking, among others.
  # This will be used only when running on OpenShift:
  # https://docs.openshift.com/container-platform/4.9/authentication/managing-security-context-constraints.html#default-sccs_configuring-internal-oauth
  resources: ["securitycontextconstraints"]
  resourceNames: ["privileged"]
  verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alterseccomp-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: alterseccomp
  namespace: alterseccomp
roleRef:
  kind: ClusterRole
  name: alterseccomp-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alterseccomp
  namespace: alterseccomp
  labels:
    k8s-app: alterseccomp
spec:
  selector:
    matchLabels:
      k8s-app: alterseccomp
  template:
    metadata:
      labels:
        k8s-app: alterseccomp
      annotations:
        container.apparmor.security.beta.kubernetes.io/alterseccomp: "unconfined"
    spec:
      serviceAccount: alterseccomp
      hostPID: false
      hostNetwork: false
      containers:
      - name: alterseccomp
        terminationMessagePolicy: FallbackToLogsOnError
        image: ghcr.io/alban/alterseccomp:latest
        imagePullPolicy: Always
        command: ["alterseccomp"]
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        env:
        - name: HOST_ROOT
          value: "/host"
        securityContext:
          seLinuxOptions:
            type: "spc_t"
          capabilities:
            add:
              - SYS_ADMIN
              - SYSLOG
              - SYS_PTRACE
              - SYS_RESOURCE
              - IPC_LOCK
        volumeMounts:
        - name: host
          mountPath: /host
        - name: run
          mountPath: /run
        - name: modules
          mountPath: /lib/modules
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: bpffs
          mountPath: /sys/fs/bpf
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: host
        hostPath:
          path: /
      - name: run
        hostPath:
          path: /run
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: modules
        hostPath:
          path: /lib/modules
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
